// examples/react/App.tsx
// src/App.tsx — Vite + React 19 SPA.
//
// The @nlqdb/react wrapper gives <NlqData> the JSX-native prop names
// (camelCase, typed event handlers) without giving up the custom
// element — under the hood it just renders <nlq-data>. <NlqScript>
// injects the elements.nlqdb.com loader once per page.
//
// This is the solo-builder's alternative to the Next.js example:
// same persona (P1 Maya), same goal ("upcoming meals this week"),
// different runtime (no SSR, no app router — just Vite).

import { NlqData, NlqScript, type NlqDataLoadDetail } from "@nlqdb/react";

const apiKey = import.meta.env.VITE_NLQDB_KEY ?? "pk_live_REPLACE_ME";

export default function App() {
  return (
    <>
      <NlqScript />
      <main>
        <h1>Upcoming meals this week</h1>
        <NlqData
          goal="upcoming meals this week, soonest first"
          apiKey={apiKey}
          template="table"
          refresh="30s"
          onLoad={({ rows, cached }: NlqDataLoadDetail) =>
            console.info("nlq-data loaded", { rows, cached })
          }
        />
      </main>
    </>
  );
}

// examples/vue/App.vue
<!--
  src/App.vue — Vite + Vue 3.5 SPA.

  The @nlqdb/vue wrapper gives <NlqData> a typed defineComponent with
  Vue-idiomatic `:api-key` bindings and `@load`/`@error` emits.

  This is the solo-builder's alternative to the Nuxt example: same
  framework family, smaller footprint, no SSR — useful when Maya wants
  to publish a static side-project on Netlify/Vercel/Cloudflare Pages
  without standing up a server.
-->

<script setup lang="ts">
import { NlqData, type NlqDataLoadDetail } from "@nlqdb/vue";

const apiKey = import.meta.env.VITE_NLQDB_KEY ?? "pk_live_REPLACE_ME";

function onLoad({ rows, cached }: NlqDataLoadDetail) {
  console.info("nlq-data loaded", { rows, cached });
}
</script>

<template>
  <main>
    <h1>Upcoming meals this week</h1>
    <NlqData
      goal="upcoming meals this week, soonest first"
      :api-key="apiKey"
      template="table"
      refresh="30s"
      @load="onLoad"
    />
  </main>
</template>
