// examples/svelte/App.svelte
<!--
  src/App.svelte — Vite + Svelte 5 (runes mode).

  The @nlqdb/svelte wrapper hides the elements.nlqdb.com loader and
  gives <NlqData> Svelte 5's lowercase `onload` callback convention.

  This is the first-timer's entry point: a CS student who picked Svelte
  because it's "the framework with the smallest mental model" and wants
  to see real rows in the browser within a minute of `npm create vite`.
-->

<script lang="ts">
  import { NlqData, type NlqDataLoadDetail } from "@nlqdb/svelte";

  const apiKey = (import.meta.env.VITE_NLQDB_KEY as string) || "pk_live_REPLACE_ME";

  function handleLoad({ rows, cached }: NlqDataLoadDetail) {
    console.info("nlq-data loaded", { rows, cached });
  }
</script>

<main>
  <h1>Users in my first DB</h1>
  <NlqData
    goal="all users, newest first"
    {apiKey}
    template="table"
    refresh="60s"
    onload={handleLoad}
  />
</main>

// examples/solid/App.tsx
// src/App.tsx — Vite + SolidJS.
//
// The @nlqdb/solid wrapper exposes <NlqData> as a Solid component
// with JSX props that compile to fine-grained reactivity — Solid only
// patches the attributes that actually changed on the underlying
// custom element.
//
// This is the analytics engineer's real-time dashboard: refresh every
// 5 seconds, surface the trace block in the console for debugging,
// and lean on Solid's no-virtual-DOM model to keep the patch cost
// near-zero even when the row count is large.

import { NlqData, type NlqDataLoadDetail } from "@nlqdb/solid";

const apiKey = (import.meta.env["VITE_NLQDB_KEY"] as string) ?? "pk_live_REPLACE_ME";

export default function App() {
  return (
    <main>
      <h1>API errors — last 5 minutes</h1>
      <NlqData
        goal="API errors in the last 5 minutes, grouped by status_code"
        apiKey={apiKey}
        template="table"
        refresh="5s"
        onLoad={({ rows, cached }: NlqDataLoadDetail) =>
          console.info("nlq-data loaded", { rows, cached })
        }
      />
    </main>
  );
}
